### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by moha-abdi** [jurihock/biquad#1]
I have tried using the bandpass filter, and with numba.jit decorator it takes an average of 6 seconds to complete which is very slow. When i got rid of it and used proper python function it was almost instant

**Comment by moha-abdi** [comment]
![image](https://github.com/jurihock/biquad/assets/83307623/90378691-3dcb-47c5-ab23-7906826a1ee0)

**Comment by jurihock** [comment]
This are my measurements:

1) Without any manipulations in `biquad.py`:

```
> time python test1.py
0:00:00.082947
python test1.py  2.20s user 0.35s system 395% cpu 0.646 total
```

2) With [this](https://github.com/jurihock/biquad/blob/02ea120b89e5368a5fc1192efa59a4da4c996efa/src/python/biquad/biquad.py#L13) and [this](https://github.com/jurihock/biquad/blob/02ea120b89e5368a5fc1192efa59a4da4c996efa/src/python/biquad/biquad.py#L173) lines commented out:

```
> time python test1.py
0:00:04.443391
python test1.py  6.38s user 0.33s system 140% cpu 4.768 total
```

Everything is perfect.

BTW, it's generally a better idea to use _scipy.signal_ functions, if the filter configuration doesn't need to be changed at runtime.

**Comment by jurihock** [comment]
Numba compilation is enforced in the constructor of the filter class. So create the filter instance once and use it multiple times.
